name: ESLint CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node_version: ${{matrix.node}}
      - name: Install modules
        run: npm i
      - name: Run ESLint
        run: npx eslint ./src/ --ext .js
